@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon May 17 19:10:49 -0700 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim BP_tb_behav -key {Behavioral:sim_1:Functional:BP_tb} -tclbatch BP_tb.tcl -protoinst "protoinst_files/VideoBuffer.protoinst" -protoinst "protoinst_files/DCM.protoinst" -view C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/GameControl_tb_behav.wcfg -log simulate.log"
call xsim  BP_tb_behav -key {Behavioral:sim_1:Functional:BP_tb} -tclbatch BP_tb.tcl -protoinst "protoinst_files/VideoBuffer.protoinst" -protoinst "protoinst_files/DCM.protoinst" -view C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/GameControl_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
