# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.cache/wt [current_project]
set_property parent.project_path C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/ClkDiv_66_67kHz.v
  C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/SPImode0.v
  C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/Binary_To_BCD.v
  C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/spiCtrl.v
  C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/PmodJSTK.v
  C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/ssdCtrl.v
  C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/ClkDiv_5Hz.v
  C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/PmodJSTK_Demo.v
}
read_xdc C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/constrs_1/new/PmodJSTK_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/kfranz/Desktop/PmodJSTK/PmodJSTK.srcs/constrs_1/new/PmodJSTK_constraints.xdc]

synth_design -top PmodJSTK_Demo -part xc7a35tcpg236-1
write_checkpoint -noxdef PmodJSTK_Demo.dcp
catch { report_utilization -file PmodJSTK_Demo_utilization_synth.rpt -pb PmodJSTK_Demo_utilization_synth.pb }
