open_project design_1_v_tpg_0_0
set_top v_tpg
open_solution "prj"
set_part {xc7z020clg400-3}
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/v_tpg_config.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/v_tpg.cpp
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/v_tpg.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/v_tpg_zoneplate.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls_video.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls_opencv.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_axi_io.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_arithm.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_core.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_fast.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_haar.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_harris.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_histogram.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_hough.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_imgbase.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_imgproc.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_io.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_mem.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_stereobm.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_types.h
add_files -cflags " -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls -I c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src " c:/Users/George/Desktop/Github/Bronco Pong/Testing stuff out/HDMI_rev1/HDMI_rev1.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/src/hls/hls_video_undistort.h

create_clock -period 20 -name ap_clk


#config_rtl -form_dsp
config_schedule -verbose
#config_interface -input_reg_mode both -output_reg_mode both


config_rtl -prefix design_1_v_tpg_0_0_
csynth_design
export_design -format ip_catalog -vendor xilinx.com -library ip -version 8.1
exit
