# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/George/Desktop/Github/Bronco Pong/Final Implementation/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1.xci
# IP: The module: 'DCM_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/George/Desktop/Github/Bronco Pong/Final Implementation/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/George/Desktop/Github/Bronco Pong/Final Implementation/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/George/Desktop/Github/Bronco Pong/Final Implementation/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/George/Desktop/Github/Bronco Pong/Final Implementation/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1.xci
# IP: The module: 'DCM_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/George/Desktop/Github/Bronco Pong/Final Implementation/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/George/Desktop/Github/Bronco Pong/Final Implementation/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/George/Desktop/Github/Bronco Pong/Final Implementation/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
