# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/constrs_1/new/test-constr.xdc

# Block Designs: bd/VideoBuffer/VideoBuffer.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VideoBuffer || ORIG_REF_NAME==VideoBuffer} -quiet] -quiet

# IP: bd/VideoBuffer/ip/VideoBuffer_blk_mem_gen_0_0/VideoBuffer_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VideoBuffer_blk_mem_gen_0_0 || ORIG_REF_NAME==VideoBuffer_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/DCM/DCM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCM || ORIG_REF_NAME==DCM} -quiet] -quiet

# IP: bd/DCM/ip/DCM_clk_wiz_0_1/DCM_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCM_clk_wiz_0_1 || ORIG_REF_NAME==DCM_clk_wiz_0_1} -quiet] -quiet

# XDC: c:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/VideoBuffer/VideoBuffer_ooc.xdc

# XDC: c:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/DCM_ooc.xdc
