set_property SRC_FILE_INFO {cfile:{C:/Users/George/Desktop/Github/Bronco Pong/Subsystems/sub_HDMIout_rev1/sub_HDMIout_rev0.srcs/constrs_1/new/Z7-20_HDMI.xdc} rfile:../../../sub_HDMIout_rev0.srcs/constrs_1/new/Z7-20_HDMI.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports { clk_100MHz }]; #IO_L12P_T1_MRCC_35 Sch=Clk
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { Reset }]; #IO_L12N_T1_MRCC_35 Sch=Reset_n
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD TMDS_33     } [get_ports { TMDS_N[3] }]; #IO_L13N_T2_MRCC_35 Sch=TMDS_N[3]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD TMDS_33     } [get_ports { TMDS_P[3] }]; #IO_L13P_T2_MRCC_35 Sch=TMDS_P[3]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D20   IOSTANDARD TMDS_33     } [get_ports { TMDS_N[0] }]; #IO_L4N_T0_35 Sch=TMDS_N[0]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD TMDS_33     } [get_ports { TMDS_P[0] }]; #IO_L4P_T0_35 Sch=TMDS_P[0]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B20   IOSTANDARD TMDS_33     } [get_ports { TMDS_N[1] }]; #IO_L1N_T0_AD0N_35 Sch=TMDS_N[1]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C20   IOSTANDARD TMDS_33     } [get_ports { TMDS_P[1] }]; #IO_L1P_T0_AD0P_35 Sch=TMDS_P[1]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A20   IOSTANDARD TMDS_33     } [get_ports { TMDS_N[2] }]; #IO_L2N_T0_AD8N_35 Sch=TMDS_N[2]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B19   IOSTANDARD TMDS_33     } [get_ports { TMDS_P[2] }]; #IO_L2P_T0_AD8P_35 Sch=TMDS_P[2]
