set_property SRC_FILE_INFO {cfile:{c:/Users/George/Desktop/Github/Bronco Pong/Subsystems/project_1/project_1.gen/sources_1/bd/clockGen/ip/clockGen_clk_wiz_0_0/clockGen_clk_wiz_0_0.xdc} rfile:../../../project_1.gen/sources_1/bd/clockGen/ip/clockGen_clk_wiz_0_0/clockGen_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:CLKGEN/clockGen_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/George/Desktop/Github/Bronco Pong/Subsystems/project_1/project_1.srcs/constrs_1/new/test-constr.xdc} rfile:../../../project_1.srcs/constrs_1/new/test-constr.xdc id:2} [current_design]
current_instance CLKGEN/clockGen_i/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
current_instance
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports { SysClk }]; #IO_L12P_T1_MRCC_35 Sch=Clk
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G15   IOSTANDARD LVCMOS33 } [get_ports { Sw[0] }]; #IO_L19N_T3_VREF_35 Sch=sw[0]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P15   IOSTANDARD LVCMOS33 } [get_ports { Sw[1] }]; #IO_L24P_T3_34 Sch=sw[1]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W13   IOSTANDARD LVCMOS33 } [get_ports { Sw[2] }]; #IO_L4N_T0_34 Sch=sw[2]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS33 } [get_ports { Sw[3] }]; #IO_L9P_T1_DQS_34 Sch=sw[3]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { Reset }]; #IO_L12N_T1_MRCC_35 Sch=Reset_n
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD TMDS_33     } [get_ports { TMDS_N[3] }]; #IO_L13N_T2_MRCC_35 Sch=TMDS_N[3]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD TMDS_33     } [get_ports { TMDS_P[3] }]; #IO_L13P_T2_MRCC_35 Sch=TMDS_P[3]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D20   IOSTANDARD TMDS_33     } [get_ports { TMDS_N[0] }]; #IO_L4N_T0_35 Sch=TMDS_N[0]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD TMDS_33     } [get_ports { TMDS_P[0] }]; #IO_L4P_T0_35 Sch=TMDS_P[0]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B20   IOSTANDARD TMDS_33     } [get_ports { TMDS_N[1] }]; #IO_L1N_T0_AD0N_35 Sch=TMDS_N[1]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C20   IOSTANDARD TMDS_33     } [get_ports { TMDS_P[1] }]; #IO_L1P_T0_AD0P_35 Sch=TMDS_P[1]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A20   IOSTANDARD TMDS_33     } [get_ports { TMDS_N[2] }]; #IO_L2N_T0_AD8N_35 Sch=TMDS_N[2]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B19   IOSTANDARD TMDS_33     } [get_ports { TMDS_P[2] }]; #IO_L2P_T0_AD8P_35 Sch=TMDS_P[2]
