# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Jonathan/Documents/project_1/.Xil/Vivado-8224-DESKTOP-9SKUCS4/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-3
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/clockGen/ipshared/d0f7 {
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/clockGen/ipshared/d0f7 {
      c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/VideoBuffer/synth/VideoBuffer.v
      c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/clockGen/synth/clockGen.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/HDMI_FrameGen_top.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/HDMI_FrameRead.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/HDMI_Out.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/HDMI_PixelROM.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/HDMI_TX.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/HDMI_Timing.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/InputRead.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/Mem_Timing.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/Mem_Writer.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/TMDS-rev2.v
      C:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/VideoBuffer/hdl/VideoBuffer_wrapper.v
      C:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/clockGen/hdl/clockGen_wrapper.v
      C:/Users/Jonathan/Documents/project_1/project_1.srcs/sources_1/new/test_top.v
    }
      rt::read_verilog -include c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/clockGen/ipshared/d0f7 {
      c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/clockGen/ip/clockGen_clk_wiz_0_0/clockGen_clk_wiz_0_0_clk_wiz.v
      c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/clockGen/ip/clockGen_clk_wiz_0_0/clockGen_clk_wiz_0_0.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/VideoBuffer/ipshared/2985/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib c:/Users/Jonathan/Documents/project_1/project_1.gen/sources_1/bd/VideoBuffer/ip/VideoBuffer_blk_mem_gen_0_0/synth/VideoBuffer_blk_mem_gen_0_0.vhd
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top test_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Jonathan/Documents/project_1/.Xil/Vivado-8224-DESKTOP-9SKUCS4/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
