# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Z7-20_HDMI.xdc

# Block Designs: bd/ClockGen/ClockGen.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ClockGen || ORIG_REF_NAME==ClockGen} -quiet] -quiet

# IP: bd/ClockGen/ip/ClockGen_clk_wiz_0_0/ClockGen_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ClockGen_clk_wiz_0_0 || ORIG_REF_NAME==ClockGen_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/George/Desktop/Github/Bronco Pong/Subsystems/sub_HDMIout_rev1/sub_HDMIout_rev0.gen/sources_1/bd/ClockGen/ClockGen_ooc.xdc
