# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/.Xil/Vivado-20280-DESKTOP-MB5IJCE/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/ipshared/d0f7
    C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/ip/ila_0_SPI
  } {
      G:/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      G:/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/ipshared/d0f7
    C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/ip/ila_0_SPI
  } {
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/.Xil/Vivado-20280-DESKTOP-MB5IJCE/realtime/VideoBuffer_blk_mem_gen_0_0_stub.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/.Xil/Vivado-20280-DESKTOP-MB5IJCE/realtime/DCM_clk_wiz_0_1_stub.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/.Xil/Vivado-20280-DESKTOP-MB5IJCE/realtime/ila_0_SPI_stub.v
      c:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/VideoBuffer/synth/VideoBuffer.v
      c:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/synth/DCM.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/BallCollision.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/BallCollision_top.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/ClkDiv_66_67kHz.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/DCM/hdl/DCM_wrapper.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/Display_top.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/GameControlTimer.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/GameControl_top.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/GameTimer.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/Game_state.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/HDMI_FrameGen_top.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/HDMI_FrameRead.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/HDMI_Out.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/HDMI_PixelROM.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/HDMI_TX.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/HDMI_Timing.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/JstkPmod_top.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/Mem_Timing.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/Mem_Writer.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/PMOD_5HzSampler.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/PaddlePos.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/PmodJSTK.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/SPImode0.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/TMDS-rev2.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.gen/sources_1/bd/VideoBuffer/hdl/VideoBuffer_wrapper.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/collisionAddOn.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/spiCtrl.v
      C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/ETE4451_BroncoPong.srcs/sources_1/new/BP_top.v
    }
      rt::read_vhdl -lib xpm G:/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top BP_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/George/Desktop/ETE4451_BroncoPong_rev2/ETE4451_BroncoPong/.Xil/Vivado-20280-DESKTOP-MB5IJCE/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
