webtalk_init -webtalk_dir C:/Users/George/Desktop/Github/Bronco Pong/Subsystems/sub_HDMIout_rev1/sub_HDMIout_rev0.sim/sim_1/behav/xsim/xsim.dir/HDMI_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr  8 11:09:40 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b976a7e5-7a27-403c-9c64-60a273a82150" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e38a8c239cb0406cad50e75fa267155b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700 Eight-Core Processor          " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3668 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "45001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "31.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14628_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2323257466 -regid "" -xml C:/Users/George/Desktop/Github/Bronco Pong/Subsystems/sub_HDMIout_rev1/sub_HDMIout_rev0.sim/sim_1/behav/xsim/xsim.dir/HDMI_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/George/Desktop/Github/Bronco Pong/Subsystems/sub_HDMIout_rev1/sub_HDMIout_rev0.sim/sim_1/behav/xsim/xsim.dir/HDMI_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/George/Desktop/Github/Bronco Pong/Subsystems/sub_HDMIout_rev1/sub_HDMIout_rev0.sim/sim_1/behav/xsim/xsim.dir/HDMI_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
