@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Apr 14 16:22:41 -0700 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim test_tb_behav -key {Behavioral:sim_1:Functional:test_tb} -tclbatch test_tb.tcl -protoinst "protoinst_files/VideoBuffer.protoinst" -protoinst "protoinst_files/clockGen.protoinst" -view C:/Users/George/Desktop/Github/Bronco Pong/Subsystems/project_1/test_tb_behav1.wcfg -log simulate.log"
call xsim  test_tb_behav -key {Behavioral:sim_1:Functional:test_tb} -tclbatch test_tb.tcl -protoinst "protoinst_files/VideoBuffer.protoinst" -protoinst "protoinst_files/clockGen.protoinst" -view C:/Users/George/Desktop/Github/Bronco Pong/Subsystems/project_1/test_tb_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
